### ISSUE TITLE
Getting blank content and transition not working as expected.

### ISSUE THREAD

**Issue by grahammccarthy** [szk-atmosphere/SAInboxViewController#13]
Hello,
I have added the library and followed the directions for implementation (including using the example project).  I am coming across a weird issue.

When I view the page that extends from SAInboxViewController, I see blank states where my data should be.  And when I click on one of those blank states I get a Push transition, not the desired Google Inbox style transition.

Do you have ideas of what the problem might be that is causing this?I suspect it is because I use Interface builder for layout, and since the library has me not using my typical @IBOutlet weak var tableView: UITableView! line, I feel like this is the root of my problem. 

The class extending from SAInboxViewController:
![image](https://cloud.githubusercontent.com/assets/1336930/14442503/160d919c-0008-11e6-89fe-fb4bc4b807d5.png)

The class extending from SAInboxDetailViewController:
![image](https://cloud.githubusercontent.com/assets/1336930/14442516/27d0f270-0008-11e6-8d25-77d5ffbab89d.png)

any assistance would be greatly appreciated.

thanks!

**Comment by szk-atmosphere** [comment]
Thank you for your question!

`SAInboxViewController` and `SAInboxDetailViewController` already have `UITableView` property.
You have to use that `tableView`.

Please try it.

**Comment by grahammccarthy** [comment]
I think the issue is that I've used Interface builder to design the cells, and when I use the `tableView` from `SAInboxViewController` it doesn't know how to render my cells.  Is there a way to hook up your `SAInboxViewController` `tableView` to interfacebuilder?

Thanks!

**Comment by grahammccarthy** [comment]
I tried a few things but couldn't get to work with interface. the only way I could get it to work was to pull out my cells into their own .xib files and reference them through code.
